### ISSUE TITLE
glitterkitten.co.uk causes a 500 error

### ISSUE THREAD

**Issue by moggers87** [iliana/emojos.in#14]
This is the url: https://emojos.in/glitterkitten.co.uk

I don't have any more information than that, but I figure something other than an ugly 500 error page should be displayed.

(and thank you for this useful tool!)

**Comment by iliana** [comment]
Looks like glitterkitten.co.uk's custom emoji endpoint is modified to require authentication.

```
$ curl https://glitterkitten.co.uk/api/v1/custom_emojis
{"error":"This method requires an authenticated user"}
```

But yes, the error could be much nicer.

**Comment by renatolond** [comment]
Hi! Thanks for your work in this :)
I was having the same issue on masto.donte.com.br, investigated a bit and I've created a PR to make the error more clear.
It doesn't seem like there's a workaround for now, except for requiring the user to login to be able to see the endpoint.

**Comment by iliana** [comment]
@renatolond's PR has been deployed :)
