### ISSUE TITLE
Pleroma compatibility

### ISSUE THREAD

**Issue by lanodan** [iliana/emojos.in#4]
It seems to be incompatible for some reason with pleroma, even through it have mastodon API too.
I also looked at my server’s log and nothing seems to be wrong.

Tested with:
* ``social.hacktivis.me`` (my instance)
* ``pleroma.soykaf.com`` (lead dev instance)

**Comment by ghost** [comment]
just remove the need of `visible_in_picker` in https://github.com/ilianaw/emojos.in/blob/mistress/emojos.py#L31
or add `visible_in_picker` in each of the pleromas `custom_emojis`

**Comment by lanodan** [comment]
I discovered that few minutes later.
I think emojos.in should fix it… documentation of mastodon API is quite liberal anyway (it just says lists, there is nothing about format) but it could be easy to fix on pleroma's side too, I guess I'll wait for iliana's opinion on it and maybe pleroma's devs if needed/wanted.
